### ISSUE TITLE
Update ExecCredential to work for v1beta1

### ISSUE THREAD

**Issue by anushas-dev** [fidelity/awsrun#29]
```awsrun kubectl get pods -A --region us-east-1 | grep -v Running``` leads to the below error:
Unable to connect to the server: getting credentials: decoding stdout: no kind "ExecCredential" is registered for version "client.authentication.k8s.io/v1alpha1" in scheme "pkg/client/auth/exec/exec.go:62"

**Comment by pkazmier** [comment]
See this commit: https://github.com/fidelity/awsrun/commit/55f3a58c25a64b856b8e97b3aa535a6299fc586c

**Comment by anushas-dev** [comment]
Thank you @pkazmier,
I tried reinstalling awsrun latest, I still seemed to hit the same error with below versions:
awsrun --version
awsrun 3.0.0

kubectl version --short
Client Version: v1.26.1

aws --version
aws-cli/1.21.0 Python/3.10.10 Linux/5.4.0-148-generic botocore/1.24.46  
turns out awscli older version was to be upgraded, once I upgraded to aws-cli/2.9.22, worked like a charm.
thank you!
