### ISSUE TITLE
Credentials plugin awsrun.plugins.creds.aws.SAML doesn't support IDP's post forms authentication 

### ISSUE THREAD

**Issue by RobertShan2000** [fidelity/awsrun#30]
In some case, the SAML auth IDP only supports post forms authentication. And our SAML credentials plugin only support get method so far. we had better make some code enhancement to support this use case. Please refer to the code https://github.com/fidelity/awsrun/blob/master/src/awsrun/session/aws.py#L417

**Comment by pkazmier** [comment]
Good suggestion! I'll add a configuration option to allow one to specify the HTTP method (GET/POST) when I return from vacation next week.

**Comment by RobertShan2000** [comment]
The issue is fixed with https://github.com/fidelity/awsrun/pull/31
