### ISSUE TITLE
No tag for v2.3.1?

### ISSUE THREAD

**Issue by lorengordon** [fidelity/awsrun#8]
Not really a big deal I suppose, since it's not published to pypi, but found this project recently and when I installed it today I noticed that I got v2.3.1, but that the repo is only tagged with v2.3.0. Figured someone missed the tag in the release process?

**Comment by pkazmier** [comment]
I simply forgot to push the tag up. All set now. Thanks!

**Comment by pkazmier** [comment]
And, yes, I really should push to pypi. I'll do this soon.

**Comment by lorengordon** [comment]
Awesome, thanks!

**Comment by pkazmier** [comment]
FYI. I've uploaded awsrun to pypi.

https://pypi.org/project/awsrun/
